### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by B3rt** [AdyRock/com.smartthings#12]
Is it possible to add source/input select for the Samsung soundbars?

The device is already present and select-able in the app, also almost all functions can be changed in Homey but i do miss the option to change the input source such as source: D.IN hdmi1, hdmi2, BT, wifi
If possible please also and action cards to select them directly:  
THEN change input to : hdmi
(if possible also: AND input is (not) hdmi2)

Thx..

**Comment by AdyRock** [comment]
In theory it is possible. The issue is each device has a different list / order of items and Homey has no way to make dynamic lists in the device panel.

I have been asking Athom if they can implement it but so far no feedback from them.

Edit: I will have a think about it to try and figure out a way around it.

**Comment by B3rt** [comment]
Thx.

The samsung wireless Audio Multiroom app from Bjornar Almli (in homey app store) has solved this, with that app you can choose the source  (but this app is failing on power on/off etc).
I have no idea how they did this.......

**Comment by AdyRock** [comment]
Does that support one specific device?
It's possible to have a predefined list but as my app is generic it's not so easy.

**Comment by B3rt** [comment]
no it support all soundbars, but it seems that they work all the same.
