### ISSUE TITLE
Danalock(Zigbee) via Smartthings

### ISSUE THREAD

**Issue by Kristianbraaten** [AdyRock/com.smartthings#16]
Hi

Im going from Smartthings to Homey, but since Homey doesn't support Danalock V3 with Zigbee I was wondering if it's possible to control the Danalock via my old Smartthings hub? I have installed your app and it finds my Smartthings devices and the Danalock, but it only shows me battery status. Any chance to implement more functions to the Danalock?

**Comment by AdyRock** [comment]
Sorry for the delay in replying.
In the Homey app, could you first go through the Add Device procedure 9no need to actually add anything but get to the screen where it lists the discovered devices) and then open More > Apps > SmartThings > Configure App > Detected. Copy the contents of the log and paste into a reply. That should show me what capabilities the lock has so I can add them to the app.
Note: the information is harmless without your account key but if you want to remove any ID then that is not a problem.

**Comment by Kristianbraaten** [comment]
{
  "items": [
    {
      "deviceId": "7f74817d-74d6-4a26-8dac-0dd3c99a96f4",
      "name": "Multipurpose Sensor",
      "label": "Garasjeport",
      "manufacturerName": "SmartThings",
      "presentationId": "SmartThings-smartthings-SmartSense_Multi_Sensor",
      "deviceManufacturerCode": "Samjin",
      "locationId": "09f51bce-1ef1-4d88-9db7-f5a627399217",
      "roomId": "02161f5c-1776-4ac2-aa45-069869648820",
      "deviceTypeId": "52517166-43f9-4cbf-8bc2-7da4e8df5614",
      "deviceTypeName": "SmartSense Multi Sensor",
      "deviceNetworkType": "ZIGBEE",
      "components": [
        {
          "id": "main",
          "label": "Garasjeport",
          "capabilities": [
            {
              "id": "temperatureMeasurement",
              "version": 1
            },
            {
              "id": "battery",
              "version": 1
            },
            {
              "id": "contactSensor",
              "version": 1
            },
            {
              "id": "configuration",
              "version": 1
            },
            {
              "id": "threeAxis",
              "version": 1
            },
            {
              "id": "accelerationSensor",
              "version": 1
            },
            {
              "id": "refresh",
              "version": 1
            },
            {
              "id": "sensor",
              "version": 1
            },
            {
              "id": "healthCheck",
              "version": 1
            }
          ],
          "categories": [
            {
              "name": "MultiFunctionalSensor",
              "categoryType": "manufacturer"
            }
          ]
        }
      ],
      "parentDeviceId": "b2e0b1dd-1290-48a2-80e0-7fa1525bfdb7",
      "dth": {
        "completedSetup": true,
        "deviceNetworkType": "ZIGBEE",
        "deviceTypeId": "52517166-43f9-4cbf-8bc2-7da4e8df5614",
        "deviceTypeName": "SmartSense Multi Sensor",
        "executingLocally": true,
        "hubId": "b2e0b1dd-1290-48a2-80e0-7fa1525bfdb7",
        "networkSecurityLevel": "UNKNOWN"
      },
      "type": "DTH",
      "restrictionTier": 0
    },
    {
      "deviceId": "a7a14454-b24a-4c90-8343-4f5448ef1d02",
      "name": "SmartThings Outlet",
      "label": "Garasjelys",
      "manufacturerName": "SmartThings",
      "presentationId": "SmartThings-smartthings-SmartPower_Outlet",
      "deviceManufacturerCode": "SmartThings",
      "locationId": "09f51bce-1ef1-4d88-9db7-f5a627399217",
      "roomId": "02161f5c-1776-4ac2-aa45-069869648820",
      "deviceTypeId": "575cca07-1d9f-4b3d-9fda-c663d8d53051",
      "deviceTypeName": "SmartPower Outlet",
      "deviceNetworkType": "ZIGBEE",
      "components": [
        {
          "id": "main",
          "label": "Garasjelys",
          "capabilities": [
            {
              "id": "switch",
              "version": 1
            },
            {
              "id": "configuration",
              "version": 1
            },
            {
              "id": "refresh",
              "version": 1
            },
            {
              "id": "powerMeter",
              "version": 1
            },
            {
              "id": "sensor",
              "version": 1
            },
            {
              "id": "actuator",
              "version": 1
            },
            {
              "id": "healthCheck",
              "version": 1
            },
            {
              "id": "outlet",
              "version": 1
            }
          ],
          "categories": [
            {
              "name": "SmartPlug",
              "categoryType": "manufacturer"
            }
          ]
        }
      ],
      "parentDeviceId": "b2e0b1dd-1290-48a2-80e0-7fa1525bfdb7",
      "dth": {
        "completedSetup": true,
        "deviceNetworkType": "ZIGBEE",
        "deviceTypeId": "575cca07-1d9f-4b3d-9fda-c663d8d53051",
        "deviceTypeName": "SmartPower Outlet",
        "executingLocally": true,
        "hubId": "b2e0b1dd-1290-48a2-80e0-7fa1525bfdb7",
        "networkSecurityLevel": "UNKNOWN"
      },
      "type": "DTH",
      "restrictionTier": 0
    },
    {
      "deviceId": "e34dee7f-59c3-47aa-b6f6-a54de3819096",
      "name": "Danalock Door Lock",
      "label": "Danalock Door Lock",
      "manufacturerName": "SmartThings",
      "presentationId": "generic-lock-2",
      "deviceManufacturerCode": "Danalock",
      "locationId": "09f51bce-1ef1-4d88-9db7-f5a627399217",
      "roomId": "90b27d2e-83ba-417a-a73c-b0b9a90b6c9c",
      "deviceTypeId": "77133b2c-359b-4828-bad9-93f57603b1cd",
      "deviceTypeName": "ZigBee Lock Without Codes",
      "deviceNetworkType": "ZIGBEE",
      "components": [
        {
          "id": "main",
          "label": "Danalock Door Lock",
          "capabilities": [
            {
              "id": "battery",
              "version": 1
            },
            {
              "id": "configuration",
              "version": 1
            },
            {
              "id": "lock",
              "version": 1
            },
            {
              "id": "refresh",
              "version": 1
            },
            {
              "id": "sensor",
              "version": 1
            },
            {
              "id": "actuator",
              "version": 1
            },
            {
              "id": "healthCheck",
              "version": 1
            }
          ],
          "categories": [
            {
              "name": "SmartLock",
              "categoryType": "manufacturer"
            }
          ]
        }
      ],
      "createTime": "2021-08-26T17:41:20.970Z",
      "parentDeviceId": "b2e0b1dd-1290-48a2-80e0-7fa1525bfdb7",
      "dth": {
        "completedSetup": true,
        "deviceNetworkType": "ZIGBEE",
        "deviceTypeId": "77133b2c-359b-4828-bad9-93f57603b1cd",
        "deviceTypeName": "ZigBee Lock Without Codes",
        "executingLocally": true,
        "hubId": "b2e0b1dd-1290-48a2-80e0-7fa1525bfdb7",
        "networkSecurityLevel": "UNKNOWN"
      },
      "type": "DTH",
      "restrictionTier": 0
    },
    {
      "deviceId": "b2e0b1dd-1290-48a2-80e0-7fa1525bfdb7",
      "name": "SmartThings v3 Hub",
      "label": "SmartThings Hub",
      "manufacturerName": "SmartThings",
      "presentationId": "SmartThings-smartthings-hub",
      "locationId": "09f51bce-1ef1-4d88-9db7-f5a627399217",
      "components": [
        {
          "id": "main",
          "capabilities": [
            {
              "id": "bridge",
              "version": 1
            }
          ],
          "categories": [
            {
              "name": "Hub",
              "categoryType": "manufacturer"
            }
          ]
        }
      ],
      "childDevices": [
        {
          "deviceId": "7f74817d-74d6-4a26-8dac-0dd3c99a96f4"
        },
        {
          "deviceId": "a7a14454-b24a-4c90-8343-4f5448ef1d02"
        },
        {
          "deviceId": "e34dee7f-59c3-47aa-b6f6-a54de3819096"
        }
      ],
      "profile": {
        "id": "f6769ddf-caa6-309c-800a-f9944b60b014"
      },
      "type": "HUB",
      "restrictionTier": 0
    }
  ],
  "_links": {}
}

**Comment by Kristianbraaten** [comment]
Any progress? :)

**Comment by AdyRock** [comment]
Ah, sorry, I completely forgot. I have been working on old requests on my other apps so this one slipped through. 
I will look when I get home. 
Again, so sorry for taking so long.

**Comment by AdyRock** [comment]
I have published a new version in the HCS. Could you try it and let me know how it goes?

**Comment by Kristianbraaten** [comment]
Worked perfectly👍

Få Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Strike2001** [comment]
@Kristianbraaten 
can i ask you something ? 
how long did you use the danalock since buying and +- how often do you open close the door.

i had 3 devices ( zwave, all runs in  hardware mailfunction ( every x days the forgot the positions. battery consumed is so high. and the signal power is so low that a bride 5 meters away get errors true . than the two different companies .de / . com are different. and the the api is useless . the had a new company tedee , it is the same scrap as before. i also have a zigbee version ovp here and a the fourth replaced from zwave the send me a homekit version 🤦‍♀️ . ( if you want a really good smartlock with all what you need , local api , bluetooth , wifi , and cloud connection , battery powered or via powercables i can say buy a nuki smartlock / smartdoor. you will be happier ;) 
p.s. all replacements was different hardware revision's but the errors comes back back and back ( what a danalock would make crazy is when you use a key , a smartphone , a api user and and somebody maybekids they turn the knob inside . i promiss that you get the same error where the lock forgot positions ( so in worse case the lock show unlocked , but is completely locked , and when you open with latch it it turns not fully from end to end. and you unlock , than save the postion as closed so that you can open door more and more till its open . and when this comes to often the device has so hard mailfunction that it goes scrap.then the stupid cylinders are also not secure that you must use. a only thing is the lock to set to turn every time to endpoints but so you can not see if the lock is 🔒 or not . and that is not smart 🤣. ps nuki also have a door sensor built in( beta option) and you can set the rsi of bt and don t need a beacon  for it , that i have here too. and no fob usement more is also false infos to the users that are waiting for the fob v2 (never comes! ) and after tedee release they do not realy invest more time in danalock.  a tuya smartlock without cloud is better cheaper then a danalock .and the worst connection protocol with no future is zwave . i don t know any system on zwave which can music Control lights in milliseconds or is compatible with so much brands .(zigbee +homekit that must they do better . to prevent wrong connection errors or device is offline states. but with that i can live but i m changing more and more devices with zigbee and conbee stick , dresden electronic software. better then every all in one zigbee hub you can by (xiomii , hue, ikea🤣 , .... ) 

and my last question how did you connect the zigbee version to smartthings via the S.Hub , or with a zigbee router ( like conbee stick /zigbeemqtt and the api. ( p.s if you want a ovp zigbee version too i will sell my lock for 80-90€ with beacon too for 100 complete incl. shipments inside eu with tracking ) 

😉 
since nuki ( no errors , no manual recalibration , no connection issues more . by danalock my realkey was min all 1,5 weeks a must usement . nuki not on time i must go my keysave which is located by a neighboor . i use the lock and the opener for doorbell etc and i 😍😍 this system as my tado heating system.i can give you Details if you want to know more about it.

**Comment by AdyRock** [comment]
As I don't have the lock myself I can't answer your questions and it seems Kristianbraaten is not seeing the questions.
If there is no more activity here then I will close the topic.
Sorry I couldn't be more helpful.
