### ISSUE TITLE
SmartThings 2 shows wrong time for washer and dryer.

### ISSUE THREAD

**Issue by StaffordBully** [AdyRock/com.smartthings#39]
SmartThings 2 in HCS shows wrong time for washer and dryer. time is 1 hour behind.

**Comment by AdyRock** [comment]
Thank you for letting me know. I think this is because Homey used to have the current time zone set, so dates were in your local time, but they then switched to fixing all Homey's to UTC. So now the apps have to do the conversion from UTC to local time.
Can you confirm if your local time is 1 hour different to UTC?

**Comment by StaffordBully** [comment]
Legal time in Belgium is now 

UTC + 1 hour in winter and 
UTC + 2 hours in summer.
