### ISSUE TITLE
sorry i did not know how to contact you..

### ISSUE THREAD

**Issue by supertabouret** [AdyRock/com.smartthings#9]
Hello Adrian,
I am sorry i did not know how to contact you elsewhere.

Having found your awsome code about ST devices to HOMEY i was wondering if the opposite would work ?
HOMEY devices to ST

Many thanks for all you did for the community
We are all gratefull
Matt

**Comment by AdyRock** [comment]
It's possible to make it work the other way, but that requires creating a SmartApp, which is a really big pain. For some reason Samsung have wandered off into the wilderness when they came up with the specification for those.
As far as I can see it's possible for an individual developer to create a personal smartapp but to create a shared one requires having a business account.
I have been trying to work out for a long time how to make a SmartApp just so I can uses subscriptions to get notifications instead of polling, but I have failed so far at the authentication stage. You can't use a PAT for subscriptions, so somehow, the SmartApp is supposed to use an oAuth token that is provided by the webhook, but I can't seem to get the callbacks to work, apart from the initial one.

**Comment by supertabouret** [comment]
SmartApps are self-published only, this means each user must register them at the Developer Workspace to be able to install them. The way to publish them nowadays is by sharing the SmartApp source code.
The one that needs an approved organization is the OAuth Integration, which allows third-party clouds to connect to the SmartThings environment.
